#!/bin/bash
#set -x # debug
set -e # fail deployment if something goes wrong

REPO_URL=$(git config --local remote.origin.url)
DOCU_ROOT="/srv/www/vhosts/docs.grommunio.com/htdocs"

DOC_RELEASE="`date +%y.%m`"
DOC_RELEASEFULL="`date +%Y.%m.%d`"

declare -a AVAIL_MANUAL=("main" "admin" "user" "web" "man" "dev" "migration")

if [ -z "$1" ]; then
	declare -a BUILD_MANUAL=("main" "admin" "user" "web" "man" "dev" "migration")
elif [[ ! " ${AVAIL_MANUAL[@]} " =~ " ${1} " ]]; then
	echo "No manual name given. Specify a valid manual to be built. Current valid manuals are:"
	printf '%s\n' "${AVAIL_MANUAL[@]}" | sed 's#^#-> #'
	exit 1
else
	declare -a BUILD_MANUAL=("$1")
fi

for MANUAL in ${BUILD_MANUAL[@]}; do

	sed -i "s#^version =.*#version = \'${DOC_RELEASE}\'##g" ${MANUAL}/conf.py
	sed -i "s#^release =.*#release = \'${DOC_RELEASEFULL}\'##g" ${MANUAL}/conf.py

	if [ "${MANUAL}" == "man" ]; then
		pushd man
			./generate-man-pages.sh
		popd
	elif [ "${MANUAL}" == "dev" ]; then
		pushd dev
			./fetch-current-openapi.sh
		popd
	elif [ "${MANUAL}" == "admin" ]; then
		pushd admin
			./do-admin-cli.sh
		popd
	fi

	for RSTFILE in ${MANUAL}/*.rst; do
		if [[ ! " ${RSTFILE} " =~ " ${MANUAL}/legal_notice.rst " ]]; then
			echo '' >> ${RSTFILE}
			cat ${MANUAL}/meta.txt >> ${RSTFILE}
		fi
	done

	make html DOCDIR=${MANUAL} BUILDDIR=${MANUAL}-build
	# ref: https://web.dev/font-display/
	sed -i 's#@font-face{#@font-face{font-display:swap;#' ${MANUAL}-build/html/_static/css/badge_only.css ${MANUAL}-build/html/_static/css/theme.css
	# ref: https://web.dev/render-blocking-resources
	sed -i -e 's#rel="stylesheet" href="_static/pygments.css" type="text/css"#rel="preload" href="_static/pygments.css" as="style" crossOrigin="anonymous" onload='this.rel=\'stylesheet\''#' ${MANUAL}-build/html/*.html

	if [ "${MANUAL}" == "dev" ]; then
		sed -i -e 's#<body>#<body><style>.operation-samples[_ngcontent-c9]{width:0%;background:none!important;}.operation-content[_ngcontent-c9]{width:90%;!important;}.background-actual[_ngcontent-c0]{background:none!important;}[sticky-sidebar][_ngcontent-c0]{max-width:90%;}.selected-tag[_ngcontent-c4]{margin-left:20px;}</style>#' ${MANUAL}-build/html/adminapispec.html
	fi

	if [ "${MANUAL}" != "main" ]; then
		rm -rf $DOCU_ROOT/${MANUAL}
		mkdir -p $DOCU_ROOT/${MANUAL}
		rsync -av ${MANUAL}-build/html/* $DOCU_ROOT/${MANUAL}/
		mkdir -p ${MANUAL}-build/latex
		rsync -av resources/_static/img/back_a4.png ${MANUAL}-build/latex/background.png
		make latexpdf DOCDIR=${MANUAL} BUILDDIR=${MANUAL}-build
		rsync -av ${MANUAL}-build/latex/grommunio.pdf $DOCU_ROOT/grommunio${MANUAL^}Doc.pdf
		make epub DOCDIR=${MANUAL} BUILDDIR=${MANUAL}-build
		rsync -av ${MANUAL}-build/epub/grommunio.epub $DOCU_ROOT/grommunio${MANUAL^}Doc.epub
	else
		mkdir -p $DOCU_ROOT
		rsync -av ${MANUAL}-build/html/* $DOCU_ROOT/
	fi

	METALINECOUNT=0
	for RSTFILE in ${MANUAL}/*.rst; do
		if [[ ! "${RSTFILE}" = "${MANUAL}/legal_notice.rst" ]]; then
			METALINECOUNT=`<${MANUAL}/meta.txt wc -l`
			sed -i "$(( $(wc -l <${RSTFILE})-${METALINECOUNT} )),$ d" ${RSTFILE}
		fi
	done

	#rm -rf "${MANUAL}-build"
done

service nginx restart
